-- Create medicines table
CREATE TABLE IF NOT EXISTS medicines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    description TEXT NOT NULL,
    category TEXT
);

-- Insert cleaned sample data
INSERT INTO medicines (name, description, category) VALUES
('amlodipine', 'Calcium channel blocker for high blood pressure and angina.', 'antihypertensive'),
('atenolol', 'Beta blocker for hypertension and angina.', 'antihypertensive'),
('bisoprolol', 'Selective beta-1 blocker for hypertension and heart failure.', 'antihypertensive'),
('carvedilol', 'Non-selective beta blocker with alpha-blocking activity.', 'antihypertensive'),
('clonidine', 'Alpha-2 agonist for hypertension.', 'antihypertensive'),
('enalapril', 'ACE inhibitor for high blood pressure and heart failure.', 'antihypertensive'),
('hydralazine', 'Direct vasodilator for hypertension and heart failure.', 'antihypertensive'),
('lisinopril', 'ACE inhibitor used for hypertension and heart failure.', 'antihypertensive'),
('losartan', 'Angiotensin II receptor blocker (ARB) for hypertension.', 'antihypertensive'),
('nebivolol', 'Selective beta-1 blocker with nitric oxide effect.', 'antihypertensive'),
('olmesartan', 'ARB for hypertension.', 'antihypertensive'),
('propranolol', 'Non-selective beta blocker for hypertension, angina, and migraines.', 'antihypertensive'),
('valsartan', 'ARB for hypertension and heart failure.', 'antihypertensive'),
('verapamil', 'Calcium channel blocker for hypertension and arrhythmias.', 'antihypertensive'),
('diltiazem', 'Calcium channel blocker for hypertension and angina.', 'antihypertensive'),
('nifedipine', 'Calcium channel blocker for hypertension and angina.', 'antihypertensive'),
('ramipril', 'ACE inhibitor for hypertension and heart failure.', 'antihypertensive'),
('spironolactone', 'Potassium-sparing diuretic for heart failure and hypertension.', 'diuretic'),
('chlorthalidone', 'Thiazide-like diuretic for hypertension and edema.', 'diuretic'),
('indapamide', 'Thiazide-like diuretic for hypertension and edema.', 'diuretic'),
('methyldopa', 'Alpha-2 agonist for hypertension, especially in pregnancy.', 'antihypertensive'),
('reserpine', 'Antihypertensive and antipsychotic agent.', 'antihypertensive'),
('terazosin', 'Alpha-1 blocker for hypertension and benign prostatic hyperplasia.', 'antihypertensive'),
('doxazosin', 'Alpha-1 blocker for hypertension and benign prostatic hyperplasia.', 'antihypertensive'),
('prazosin', 'Alpha-1 blocker for hypertension and PTSD-related nightmares.', 'antihypertensive'),

-- Diuretics
('furosemide', 'Loop diuretic for edema and heart failure.', 'diuretic'),
('triamterene', 'Potassium-sparing diuretic often combined with HCTZ.', 'diuretic'),
('bumetanide', 'Loop diuretic for edema and heart failure.', 'diuretic'),
('metolazone', 'Thiazide-like diuretic for edema and hypertension.', 'diuretic'),
('amiloride', 'Potassium-sparing diuretic often combined with HCTZ.', 'diuretic'),

-- COPD & Asthma
('albuterol', 'Inhaler for asthma and COPD.', 'copd'),
('salbutamol', 'Short-acting bronchodilator for asthma attacks.', 'copd'),
('tiotropium', 'Long-acting bronchodilator for COPD.', 'copd'),
('ipratropium', 'Short-acting bronchodilator for COPD.', 'copd'),
('fluticasone', 'Inhaled corticosteroid for asthma and COPD.', 'steroid'),
('budesonide', 'Inhaled corticosteroid for asthma management.', 'steroid'),
('mometasone', 'Inhaled corticosteroid for asthma.', 'steroid'),

-- Antihistamines & Allergy
('cetirizine', 'Antihistamine for allergies and hay fever.', 'allergy'),
('loratadine', 'Antihistamine for allergies and hay fever.', 'allergy'),
('fexofenadine', 'Second-generation antihistamine for allergies.', 'allergy'),
('diphenhydramine', 'Antihistamine for allergies and sleep aid.', 'allergy'),
('hydroxyzine', 'Antihistamine for anxiety and allergies.', 'allergy'),

-- OTC Medications
('omeprazole', 'Proton pump inhibitor (PPI) for GERD and ulcers.', 'otc'),
('lansoprazole', 'PPI for acid reflux and stomach ulcers.', 'otc'),
('pantoprazole', 'PPI for GERD and Zollinger-Ellison syndrome.', 'otc'),
('ranitidine', 'H2 receptor antagonist for GERD and ulcers.', 'otc'),
('famotidine', 'H2 receptor antagonist for heartburn and ulcers.', 'otc'),
('cimetidine', 'H2 blocker for acid reflux and peptic ulcers.', 'otc'),
('ibuprofen', 'NSAID used for pain, inflammation, and fever.', 'nsaid'),
('naproxen', 'NSAID for pain, inflammation, and fever.', 'nsaid'),
('diclofenac', 'NSAID for pain and inflammation.', 'nsaid'),
('acetaminophen', 'Analgesic and antipyretic for pain and fever.', 'otc'),

-- Antibiotics & Antivirals
('amoxicillin', 'Antibiotic for bacterial infections.', 'antibiotic'),
('azithromycin', 'Macrolide antibiotic for respiratory and skin infections.', 'antibiotic'),
('ciprofloxacin', 'Fluoroquinolone antibiotic for UTIs and GI infections.', 'antibiotic'),
('cephalexin', 'Cephalosporin antibiotic for skin and respiratory infections.', 'antibiotic'),
('clindamycin', 'Antibiotic for bacterial infections including skin.', 'antibiotic'),
('metronidazole', 'Antibiotic and antiprotozoal for bacterial and parasitic infections.', 'antibiotic'),
('doxycycline', 'Tetracycline antibiotic for infections and acne.', 'antibiotic'),
('valacyclovir', 'Antiviral for herpes virus infections.', 'antiviral'),
('acyclovir', 'Antiviral for herpes virus infections.', 'antiviral'),
('famciclovir', 'Antiviral for herpes virus infections.', 'antiviral'),

-- Antifungals
('fluconazole', 'Antifungal for yeast infections and fungal diseases.', 'antifungal'),
('ketoconazole', 'Antifungal for skin, nail, and systemic infections.', 'antifungal'),
('terbinafine', 'Antifungal for nail and skin infections.', 'antifungal'),
('nystatin', 'Antifungal for oral and skin yeast infections.', 'antifungal'),
('miconazole', 'Topical antifungal for skin infections.', 'antifungal'),

('alfuzosin', 'Alpha-1 blocker for benign prostatic hyperplasia.', 'antihypertensive'),
('amiodarone', 'Antiarrhythmic for atrial and ventricular arrhythmias.', 'antiarrhythmic'),
('apixaban', 'Direct oral factor Xa inhibitor for stroke prevention.', 'anticoagulant'),
('atorvastatin', 'HMG-CoA reductase inhibitor for hyperlipidemia.', 'lipid-lowering'),
('baclofen', 'Muscle relaxant for spasticity.', 'neuromuscular'),
('benazepril', 'ACE inhibitor for hypertension.', 'antihypertensive'),
('betamethasone', 'Corticosteroid for inflammation and skin conditions.', 'steroid'),
('bicalutamide', 'Antiandrogen for prostate cancer.', 'oncology'),
('bosentan', 'Endothelin receptor antagonist for pulmonary hypertension.', 'antihypertensive'),
('brimonidine', 'Alpha-2 agonist for glaucoma.', 'ophthalmic'),
('bromocriptine', 'Dopamine agonist for Parkinson’s and hyperprolactinemia.', 'neurological'),
('buspirone', 'Anxiolytic for generalized anxiety disorder.', 'anxiolytic'),
('candesartan', 'ARB for hypertension and heart failure.', 'antihypertensive'),
('capecitabine', 'Oral chemotherapy for colorectal cancer.', 'oncology'),
('carbamazepine', 'Anticonvulsant for epilepsy and trigeminal neuralgia.', 'neurological'),
('carisoprodol', 'Muscle relaxant for musculoskeletal pain.', 'neuromuscular'),
('celecoxib', 'COX-2 inhibitor NSAID for arthritis and pain.', 'nsaid'),
('ceftazidime', 'Cephalosporin antibiotic for severe bacterial infections.', 'antibiotic'),
('ceftriaxone', 'Broad-spectrum cephalosporin for infections.', 'antibiotic'),
('chlorpheniramine', 'First-generation antihistamine for allergies.', 'allergy'),
('citalopram', 'SSRI antidepressant for depression and anxiety.', 'antidepressant'),
('clobetasol', 'High-potency topical corticosteroid for skin conditions.', 'steroid'),
('clonazepam', 'Benzodiazepine for seizures and panic disorders.', 'anxiolytic'),
('clopidogrel', 'Antiplatelet agent for cardiovascular prevention.', 'anticoagulant'),
('colchicine', 'Anti-inflammatory for gout and pericarditis.', 'anti-inflammatory'),
('cyclobenzaprine', 'Muscle relaxant for acute musculoskeletal pain.', 'neuromuscular'),
('dabigatran', 'Direct thrombin inhibitor for stroke and DVT prevention.', 'anticoagulant'),
('desloratadine', 'Second-generation antihistamine for allergies.', 'allergy'),
('desmopressin', 'Synthetic vasopressin analog for diabetes insipidus.', 'endocrine'),
('dexmedetomidine', 'Sedative and analgesic for ICU patients.', 'anxiolytic'),
('dexamethasone', 'Corticosteroid for inflammation and immune response.', 'steroid'),
('diazepam', 'Benzodiazepine for anxiety, seizures, and muscle spasms.', 'anxiolytic'),
('digoxin', 'Cardiac glycoside for heart failure and atrial fibrillation.', 'cardiovascular'),
('dobutamine', 'Inotrope for heart failure and cardiogenic shock.', 'cardiovascular'),
('domperidone', 'Dopamine antagonist for nausea and gastroparesis.', 'antiemetic'),
('donepezil', 'Cholinesterase inhibitor for Alzheimer’s disease.', 'neurological'),
('duloxetine', 'SNRI for depression, anxiety, and neuropathic pain.', 'antidepressant'),
('edaravone', 'Neuroprotective for ALS.', 'neurological'),

('enoxaparin', 'LMWH for prevention and treatment of DVT and PE.', 'anticoagulant'),
('esomeprazole', 'PPI for GERD and acid-related disorders.', 'otc'),
('etanercept', 'TNF-alpha inhibitor for autoimmune diseases.', 'immunomodulator'),
('etoposide', 'Chemotherapy agent for various cancers.', 'oncology'),
('ezetimibe', 'Cholesterol absorption inhibitor for hyperlipidemia.', 'lipid-lowering'),
('fenofibrate', 'PPAR-alpha agonist for hyperlipidemia.', 'lipid-lowering'),
('fentanyl', 'Potent opioid analgesic for severe pain.', 'narcotic'),
('fluoxetine', 'SSRI antidepressant for depression and OCD.', 'antidepressant'),
('folic acid', 'Vitamin B9 supplement for anemia and pregnancy.', 'vitamin'),
('formoterol', 'Long-acting beta-2 agonist for asthma and COPD.', 'copd'),
('gabapentin', 'Neuropathic pain and anticonvulsant.', 'neurological'),
('ganciclovir', 'Antiviral for CMV infections.', 'antiviral'),
('gemfibrozil', 'PPAR-alpha agonist for hyperlipidemia.', 'lipid-lowering'),
('glimepiride', 'Sulfonylurea for type 2 diabetes.', 'diabetes'),
('glipizide', 'Sulfonylurea for type 2 diabetes.', 'diabetes'),
('glyburide', 'Sulfonylurea for type 2 diabetes.', 'diabetes'),
('hydrochlorothiazide', 'Thiazide diuretic for hypertension and edema.', 'diuretic'),
('hydrocortisone', 'Corticosteroid for inflammation and adrenal insufficiency.', 'steroid'),
('hydromorphone', 'Potent opioid for severe pain.', 'narcotic'),
('hydroxychloroquine', 'Antimalarial and immunomodulator for autoimmune diseases.', 'antimalarial'),
('ibandronate', 'Bisphosphonate for osteoporosis.', 'bone-health'),
('imatinib', 'Tyrosine kinase inhibitor for leukemia and GIST.', 'oncology'),
('indomethacin', 'NSAID for arthritis and acute pain.', 'nsaid'),
('insulin detemir', 'Long-acting insulin for diabetes management.', 'diabetes'),
('insulin glargine', 'Long-acting insulin for diabetes management.', 'diabetes'),
('insulin lispro', 'Rapid-acting insulin for post-meal glucose control.', 'diabetes'),
('insulin aspart', 'Rapid-acting insulin for post-meal glucose control.', 'diabetes'),
('isosorbide dinitrate', 'Nitrate for angina and heart failure.', 'cardiovascular'),
('isosorbide mononitrate', 'Nitrate for angina and heart failure.', 'cardiovascular'),
('ivabradine', 'Selective sinus node inhibitor for heart failure.', 'cardiovascular'),
('ketorolac', 'Potent NSAID for short-term severe pain.', 'nsaid'),
('labetalol', 'Non-selective beta and alpha-1 blocker for hypertension.', 'antihypertensive'),
('lamotrigine', 'Anticonvulsant for epilepsy and bipolar disorder.', 'neurological'),
('latanoprost', 'Prostaglandin analog for glaucoma.', 'ophthalmic'),
('levetiracetam', 'Anticonvulsant for epilepsy.', 'neurological'),
('levothyroxine', 'Synthetic thyroid hormone for hypothyroidism.', 'endocrine'),
('lidocaine', 'Local anesthetic and antiarrhythmic.', 'cardiovascular'),
('lithium', 'Mood stabilizer for bipolar disorder.', 'psychiatric'),
('lorazepam', 'Benzodiazepine for anxiety and seizures.', 'anxiolytic'),
('magnesium sulfate', 'Electrolyte for magnesium deficiency and eclampsia.', 'electrolyte'),
('meloxicam', 'NSAID for arthritis and pain.', 'nsaid'),
('memantine', 'NMDA receptor antagonist for Alzheimer’s disease.', 'neurological'),
('metformin', 'Oral medication for type 2 diabetes.', 'diabetes'),
('methadone', 'Opioid used for chronic pain and opioid dependence.', 'narcotic'),
('methimazole', 'Antithyroid drug for hyperthyroidism.', 'endocrine'),
('methylphenidate', 'Stimulant for ADHD and narcolepsy.', 'psychiatric'),
('methylprednisolone', 'Corticosteroid for inflammation and allergic reactions.', 'steroid'),
('metoclopramide', 'Dopamine antagonist for nausea, vomiting, and gastroparesis.', 'antiemetic'),
('montelukast', 'Leukotriene receptor antagonist for asthma and allergies.', 'allergy'),
('loperamide', 'Anti-diarrheal for acute and chronic diarrhea.', 'otc'),
('lovastatin', 'HMG-CoA reductase inhibitor for hyperlipidemia.', 'lipid-lowering'),
('lurasidone', 'Atypical antipsychotic for schizophrenia and bipolar disorder.', 'psychiatric'),
('metoprolol', 'Beta blocker for hypertension and heart disease.', 'antihypertensive'),
('midazolam', 'Short-acting benzodiazepine for sedation and anesthesia.', 'anxiolytic'),
('minocycline', 'Tetracycline antibiotic for acne and infections.', 'antibiotic'),
('morphine', 'Opioid analgesic for moderate to severe pain.', 'narcotic'),
('nadolol', 'Non-selective beta blocker for hypertension and arrhythmias.', 'antihypertensive'),
('naloxone', 'Opioid antagonist for overdose.', 'narcotic'),
('nevirapine', 'NNRTI antiretroviral for HIV treatment.', 'antiviral'),
('nicardipine', 'Calcium channel blocker for hypertension and angina.', 'antihypertensive'),
('nisoldipine', 'Calcium channel blocker for hypertension.', 'antihypertensive'),
('nitrofurantoin', 'Antibiotic for urinary tract infections.', 'antibiotic'),
('nitroglycerin', 'Nitrate for angina.', 'cardiovascular'),
('nizatidine', 'H2 receptor antagonist for acid reflux.', 'otc'),
('nortriptyline', 'Tricyclic antidepressant for depression and neuropathic pain.', 'antidepressant'),
('ondansetron', '5-HT3 antagonist for nausea and vomiting.', 'antiemetic'),
('oseltamivir', 'Neuraminidase inhibitor for influenza treatment.', 'antiviral'),
('oxcarbazepine', 'Anticonvulsant for epilepsy.', 'neurological'),
('oxycodone', 'Opioid for moderate to severe pain.', 'narcotic'),
('paroxetine', 'SSRI antidepressant for depression and anxiety.', 'antidepressant'),
('penicillin G', 'Antibiotic for bacterial infections.', 'antibiotic'),
('penicillin V', 'Antibiotic for bacterial infections.', 'antibiotic'),
('phenobarbital', 'Barbiturate for seizures and sedation.', 'neurological'),
('phenytoin', 'Anticonvulsant for epilepsy.', 'neurological'),
('pioglitazone', 'Thiazolidinedione for type 2 diabetes.', 'diabetes'),
('pravastatin', 'HMG-CoA reductase inhibitor for hyperlipidemia.', 'lipid-lowering'),
('prednisone', 'Corticosteroid for inflammation and autoimmune diseases.', 'steroid'),
('pregabalin', 'Neuropathic pain and anticonvulsant.', 'neurological'),
('quetiapine', 'Atypical antipsychotic for schizophrenia and bipolar disorder.', 'psychiatric'),
('risperidone', 'Atypical antipsychotic for schizophrenia and bipolar disorder.', 'psychiatric'),
('rivaroxaban', 'Direct oral factor Xa inhibitor to prevent stroke and DVT.', 'anticoagulant'),
('rosuvastatin', 'HMG-CoA reductase inhibitor for hyperlipidemia.', 'lipid-lowering'),
('sertraline', 'SSRI antidepressant for depression and anxiety.', 'antidepressant'),
('simvastatin', 'HMG-CoA reductase inhibitor for hyperlipidemia.', 'lipid-lowering'),
('sitagliptin', 'DPP-4 inhibitor for type 2 diabetes.', 'diabetes'),
('sodium valproate', 'Anticonvulsant for epilepsy and bipolar disorder.', 'neurological'),
('sotalol', 'Beta blocker with antiarrhythmic properties.', 'antiarrhythmic'),
('sucralfate', 'Gastroprotective agent for ulcers.', 'otc'),
('sulfamethoxazole-trimethoprim', 'Antibiotic combination for bacterial infections.', 'antibiotic'),
('sumatriptan', 'Serotonin agonist for migraine relief.', 'neurological'),
('tadalafil', 'PDE5 inhibitor for erectile dysfunction and pulmonary hypertension.', 'urology'),
('tamoxifen', 'Selective estrogen receptor modulator for breast cancer.', 'oncology'),
('tamsulosin', 'Alpha-1 blocker for BPH.', 'urology'),
('tetracycline', 'Antibiotic for bacterial infections.', 'antibiotic'),
('ticagrelor', 'Antiplatelet agent for cardiovascular events.', 'anticoagulant'),
('tizanidine', 'Muscle relaxant for spasticity.', 'neuromuscular'),
('topiramate', 'Anticonvulsant for epilepsy and migraine prophylaxis.', 'neurological'),
('tramadol', 'Opioid analgesic for moderate pain.', 'narcotic'),
('travoprost', 'Prostaglandin analog for glaucoma.', 'ophthalmic'),
('trihexyphenidyl', 'Anticholinergic for Parkinson’s disease.', 'neurological'),
('vancomycin', 'Glycopeptide antibiotic for severe infections.', 'antibiotic'),
('venlafaxine', 'SNRI for depression and anxiety.', 'antidepressant'),
('voriconazole', 'Antifungal for systemic fungal infections.', 'antifungal'),
('warfarin', 'Vitamin K antagonist anticoagulant for thromboembolic events.', 'anticoagulant'),
('zidovudine', 'NRTI antiretroviral for HIV treatment.', 'antiviral'),
('zolpidem', 'Sedative-hypnotic for insomnia.', 'anxiolytic'),
('zopiclone', 'Sedative-hypnotic for insomnia.', 'anxiolytic');